In [1]:
import numpy as np
import pandas as pd

In [2]:
input_array = np.array([1,2,3,4])

N = 4 #No of columns required

result = np.column_stack(input_array**(N-i-1) for i in range(0,N))

print(result)

[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  """


In [3]:
import numpy as np

In [4]:
input_array = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]) #Given Input
k=3  # Given window

In [5]:
#Moving Average function

def moving_average (inp_array,k=3):
    #In this we are using the np.cumsum to get the cumulative sum of the numbers
    #[k-1] is used to select the last value in as array
    result = [(np.cumsum(inp_array[i:i+k],dtype=float)[k-1])/k for i in range(0,(len(inp_array)-k+1))]
    return result
    

In [9]:
moving_average(input_array,k=3)


[5.0,
 4.666666666666667,
 5.666666666666667,
 6.666666666666667,
 9.666666666666666,
 28.666666666666668,
 49.333333333333336,
 72.66666666666667,
 84.0,
 93.33333333333333,
 116.33333333333333]